# Generated by Django 4.0.4 on 2022-05-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_no', models.BigIntegerField()),
                ('task', models.TextField()),
                ('desc', models.TextField()),
                ('check_task', models.BooleanField()),
            ],
        ),
    ]
