# Generated by Django 4.0.4 on 2022-05-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='task',
            field=models.CharField(max_length=200),
        ),
    ]
