# Generated by Django 4.0.4 on 2022-05-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist1', '0002_alter_list_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='task',
            field=models.TextField(),
        ),
    ]
